import './globals.css'
import { Inter } from 'next/font/google'
import { LuCrown } from 'react-icons/lu';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='navegation'>
          <a href="/">Home</a>
          <LuCrown className='firsticon'/>
          <a href="/about">About</a>
        </nav>
        {children}
        <footer className="footer">
          {/* <LuCrown/> */}
          <LuCrown className='firsticon'/>
          <a href="/about">Contato</a>
          {/* <LuCrown/> */}
          <LuCrown className='firsticon'/>
        </footer>
      </body>
    </html>
  )
}
